export const GET_ERRORS = "GET_ERRORS";
export const RESET_ERRORS = "RESET_ERRORS";

export const GET_RECIPES = "GET_RECIPES";
export const GET_RECIPE = "GET_RECIPE";
export const SET_MODAL_CONTENT = "SET_MODAL_CONTENT";
export const GET_FAVORITE_RECIPES = "GET_FAVORITE_RECIPES";
export const DELETE_RECIPE = "DELETE_RECIPE";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SET_SAVE_RECIPE_MESSAGE = "SET_SAVE_RECIPE_MESSAGE";
export const SET_DELETE_RECIPE_MESSAGE = "SET_DELETE_RECIPE_MESSAGE";
export const SET_REDIRECT_MESSAGE = "SET_REDIRECT_MESSAGE";
export const SET_WELCOME_MESSAGE = "SET_WELCOME_MESSAGE";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const SET_MENUS = "SET_MENUS";
export const SET_PAGE_TITLE = "SET_PAGE_TITLE";

