export const GET_ERRORS = "GET_ERRORS";
export const GET_RECIPES = "GET_RECIPES";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_SAVE_FEEDBACK = "GET_SAVE_FEEDBACK";
export const GET_RECIPE_BY_ID = "GET_RECIPE_BY_ID";
export const GET_PAGE_TITLE = "GET_PAGE_TITLE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_MENUS = "SET_MENUS";
export const DELETE_FEEDBACK = "DELETE_FEEDBACK";
export const GET_USER_RECIPES = "GET_USER_RECIPES";
export const SHOW_BACK_BUTTON = "SHOW_BACK_BUTTON";

